'use client';

import { useId, useMemo, type CSSProperties, type ReactNode } from 'react';
import { cn } from '@/lib/helpers';
import type { FrameInfo } from './catalog';
import type { FxSpec } from './geometry';
import { renderFrameLayers } from './render';
import './frames.css';

function Fx({ fx }: { fx: FxSpec }) {
  const style = { '--c': fx.colors, '--d': `${fx.duration}s` } as CSSProperties;
  if (fx.square) {
    return (
      <>
        <div className="mlf-fxw">
          <div className="mlf-fxs" style={style}>
            <i />
          </div>
        </div>
        <div className="mlf-fxs" style={style}>
          <i />
        </div>
      </>
    );
  }
  return (
    <>
      <div className="mlf-fx mlf-fx-blur" style={style} />
      <div className="mlf-fx" style={style} />
    </>
  );
}

/**
 * Draws one frame around `children` (the avatar content). `size` is the frame
 * box in px; the avatar occupies 68.75% of it (disc, or rounded square for
 * square frames). Requires <FrameDefs /> on the page (root layout).
 *
 * The SVG layers are injected as markup generated by the internal renderers
 * of `./raw` (constants only, no user input; the variant is reduced to
 * `S<digits>`), which keeps them identical to the validated reference.
 */
export default function FrameArt({
  frame,
  variant = '',
  size,
  label,
  className,
  children,
}: {
  frame: FrameInfo;
  variant?: string;
  size: number;
  /** Accessible label; decorative when omitted. */
  label?: string;
  className?: string;
  children?: ReactNode;
}) {
  const uid = useId();
  const layers = useMemo(() => renderFrameLayers(frame, variant, uid), [frame, variant, uid]);
  return (
    <div
      className={cn('mlf', frame.shape === 'square' && 'mlf-sq', className)}
      style={{ '--s': `${size}px`, width: size, height: size } as CSSProperties}
      role={label ? 'img' : undefined}
      aria-label={label}
      data-frame={frame.id}
    >
      {layers.fx && <Fx fx={layers.fx} />}
      {layers.under && (
        <svg viewBox="0 0 128 128" aria-hidden="true" dangerouslySetInnerHTML={{ __html: layers.under }} />
      )}
      <div className="mlf-av">{children}</div>
      {layers.over && (
        <svg viewBox="0 0 128 128" aria-hidden="true" dangerouslySetInnerHTML={{ __html: layers.over }} />
      )}
    </div>
  );
}
